# Generated by Django 4.2.1 on 2023-05-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('number_of_guests', models.IntegerField()),
                ('booking_date', models.DateTimeField()),
            ],
        ),
    ]
