# Generated by Django 4.2.1 on 2023-05-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tiltle', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=4, max_digits=9)),
                ('inventory', models.IntegerField()),
            ],
        ),
    ]
